web:
  image: nginx:latest
  ports:
    - "9000:9000"
  volumes: 
    - ./html:/usr/share/nginx/html
    - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
  links:
    - php

php:
  image: bitnami/php-fpm:latest
  volumes:
    - ./html:/usr/share/nginx/html/
  links: 
    - db

db:
  image: mysql:5.7
  restart: always
  ports:
    - "3306:3306"
  environment:
    # MYSQL_DATABASE: dashboards_api
    # - MYSQL_ROOT_PASSWORD=password
    MYSQL_ROOT_PASSWORD: root